# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-22 05:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course_picker', '0002_auto_20170522_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='courses',
            field=models.ManyToManyField(blank=True, null=True, related_name='professors', to='course_picker.Course'),
        ),
        migrations.AlterField(
            model_name='professor',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
